const ROLES = Object.freeze({
  ADMIN: 'admin',
  MANAGER: 'manager',
  MEMBER: 'member',
});

const TASK_STATUS = Object.freeze({
  TODO: 'todo',
  IN_PROGRESS: 'in_progress',
  REVIEW: 'review',
  DONE: 'done',
});

const TASK_STATUS_TRANSITIONS = Object.freeze({
  [TASK_STATUS.TODO]: [TASK_STATUS.IN_PROGRESS],
  [TASK_STATUS.IN_PROGRESS]: [TASK_STATUS.REVIEW],
  [TASK_STATUS.REVIEW]: [TASK_STATUS.DONE, TASK_STATUS.IN_PROGRESS],
  [TASK_STATUS.DONE]: [],
});

const TASK_PRIORITY = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
});

const PROJECT_STATUS = Object.freeze({
  ACTIVE: 'active',
  ARCHIVED: 'archived',
  COMPLETED: 'completed',
});

const HTTP_STATUS = Object.freeze({
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_ERROR: 500,
});

const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
});

const MAX_LOGIN_ATTEMPTS = 5;
const TOKEN_RESET_EXPIRES_HOURS = 1;
const PAGINATION_DEFAULT_LIMIT = 20;
const PAGINATION_MAX_LIMIT = 100;

module.exports = {
  ROLES,
  TASK_STATUS,
  TASK_STATUS_TRANSITIONS,
  TASK_PRIORITY,
  PROJECT_STATUS,
  HTTP_STATUS,
  ERROR_CODES,
  MAX_LOGIN_ATTEMPTS,
  TOKEN_RESET_EXPIRES_HOURS,
  PAGINATION_DEFAULT_LIMIT,
  PAGINATION_MAX_LIMIT,
};
